name: Build macOS
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Xcode Project
        run: xcodebuild -project Builds/MacOSX/Modulee.xcodeproj -configuration Release
