name: Build Linux
on:
  push:
    branches:
      - release
      - build-linux

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Rust Component
        run: |
          cd Vendor/modulee-engine-clib
          cargo build --release

      - name: Install JUCE dependencies
        run: |
          sudo apt update -qq
          sudo apt install clang \
            libasound2-dev libjack-jackd2-dev \
            ladspa-sdk \
            libcurl4-openssl-dev  \
            libfreetype-dev libfontconfig1-dev \
            libx11-dev libxcomposite-dev libxcursor-dev libxext-dev libxinerama-dev libxrandr-dev libxrender-dev \
            libwebkit2gtk-4.1-dev \
            libglu1-mesa-dev mesa-common-dev \
            -y -qq

      - name: Clone JUCE
        run: |
          git clone https://github.com/juce-framework/JUCE.git ~/JUCE

      - name: Build Project
        working-directory: Builds/LinuxMakefile
        run: make CONFIG=Release -j$(nproc)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Modulee.zip
          path: |
            Builds/LinuxMakefile/build/Modulee.vst3/Contents/x86_64-linux/Modulee.so
            Builds/LinuxMakefile/build/Modulee
